### ISSUE TITLE
[BLOCKED] MetaMask button doesn't display correctly on hover

### ISSUE THREAD

**Issue by gesquinca** [ConsenSys/rimble-web3-components#12]
We shouldn't be wrapping buttons in links.

**Comment by MikeLockz** [comment]
Blocked by https://github.com/ConsenSys/rimble-ui/issues/254

**Comment by MikeLockz** [comment]
Will require a bump to the patch version of rimble-ui

**Comment by MikeLockz** [comment]
Now blocked by https://github.com/ConsenSys/rimble-ui/issues/271

**Comment by MikeLockz** [comment]
Fixed
