### ISSUE TITLE
ConnectionBanner component

### ISSUE THREAD

**Issue by zkalman** [ConsenSys/rimble-web3-components#2]
As a dapp user, I need to know right away if my browser is not Web3-enabled or if I'm connected to the wrong network.

## Acceptance Criteria
- Should honor ThemeProvider theme
- Should allow children elements to be passed in to each state
- Should use the Flash component from rimble-ui
- Should show *notWeb3CapableBrowser* message when browser is not chrome, firefox, brave, or opera (safari, IE, Edge)
- Should show *noWalletAvailable* message when no browser web3 instance available (metamask not installed)
- Should show *onWrongNetwork* message when the current network does not match the required network
- Should not show any message when on the correct network
- Tests
- Usage documentation

- Inputs: 
  - Required browsers
  - Required networks
  - onWeb3Fallback (?)
- Outputs:
  - Flash component with *notWeb3CapableBrowser* message
  - Flash component with *noWalletAvailable* message
  - Flash component with *onWrongNetwork* message

Design something like this:
![connectionbanner](https://user-images.githubusercontent.com/6794540/56584316-895d9200-65a9-11e9-96b7-0b427652b7ba.png)

**Comment by MikeLockz** [comment]
Component npm package:
https://www.npmjs.com/package/@rimble/connection-banner

Live Demo:
https://mikelockz.github.io/rimble-app-demo/
