### ISSUE TITLE
NetworkIndicator component

### ISSUE THREAD

**Issue by zkalman** [ConsenSys/rimble-web3-components#3]
As a dapp user, I would like to know what network I am on, and what network I am supposed to be on.

## Acceptance criteria
- Display the name of the network plus whether it's the correct network based on the specified network
- Tooltip is used to clarify the icon e.g. You're on the right network, you need to switch to Rinkeby etc...
- Inputs:
  - A single input of a current network ID
  - Optional second input for required network
  - Option to override with custom network (edge case?)
  - Optional tooltip message text for each state
- Outputs:
  - Current network name
  - Boolean if correct network
  - Tooltip message text
- Tests
- Usage documentation

Design something like this:
<img width="914" alt="Screenshot 2019-04-23 09 48 15" src="https://user-images.githubusercontent.com/6794540/56586051-fc1c3c80-65ac-11e9-96c7-d800bd30912b.png">

**Comment by MikeLockz** [comment]
Component npm package:
https://www.npmjs.com/package/@rimble/network-indicator

Live Demo:
https://mikelockz.github.io/rimble-app-demo/
