### ISSUE TITLE
NetworkIndicator usage documentation

### ISSUE THREAD

**Issue by zkalman** [ConsenSys/rimble-web3-components#5]
Blocked by #3 

- [x] Overview
- [x] Installation
- [x] Usage example
- [x] Prop table
- [x] APIs/functions
- [x] Screenshots

_NOTE: This issue refers only to dev usage documentation, not design guidelines._

**Comment by MikeLockz** [comment]
Example docs:
https://www.npmjs.com/package/@mikelockzrimble/network-indicator
